name: Example pipeline that fails in tests for slice

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew test --no-daemon --stacktrace --info